## ----------------------------------------------------------------------------
## nexus | NEXT100.config.mac
##
## Configuration macro to simulate Bi-214 radioactive decays from thethe
## copper plate of the tracking plane in the NEXT-100 detector.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

##### VERBOSITY #####
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

##### GEOMETRY #####
/Geometry/Next100/elfield false
/Geometry/Next100/max_step_size 0.1 mm
/Geometry/Next100/pressure 15 bar
/Geometry/Next100/gas depletedXe


##### GENERATOR #####
/Generator/SingleParticle/particle e-
/Generator/SingleParticle/region CENTER
/Generator/SingleParticle/min_energy 2 MeV
/Generator/SingleParticle/max_energy 2 MeV

##### ACTIONS #####
/Actions/DefaultEventAction/min_energy 0.6 MeV
/Actions/DefaultEventAction/max_energy 2.55 MeV

##### PHYSICS #####
## No full simulation
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false

##### PERSISTENCY #####
/nexus/persistency/outputFile Next100_2MeV_0.1mm_2k.next
## eventType options: bb0nu, bb2nu, background
/nexus/persistency/eventType background
/nexus/random_seed 0
/nexus/persistency/start_id 0
